
# The name of the workflow execution
name: Order Large Cheese Pizza

# Event we will be listening for
on: 
  issues:
    types: [opened]
    
jobs:

  # Places an order
  order_home:

    # Will run on ubuntu
    runs-on: ubuntu-latest
    outputs:
      ERROR_MESSAGE: ${{ steps.Order-Pizza.outputs.Error_Message }}
    
    # Checking the comment body for our trigger phrase
    # If found in the body, the steps below will run
    if: (contains(github.event.issue.body,'/order pizza home'))

    # The procedural functionality of the place_order job
    steps:
    #Build Project
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '12'

    #Order Pizza
    - name: Order-Pizza
      id: Order-Pizza
      uses: polivebranch/its-pizza-time@main
      with:
        RECEIVING_ADDRESS: ${{ secrets.HOME_ADDRESS }}
        CC_NUMBER: ${{ secrets.CC_NUMBER }}
        CC_EXP: ${{ secrets.CC_EXP }}
        CC_CVV: ${{ secrets.CC_CVV }}
        CC_ZIP: ${{ secrets.CC_ZIP }}
      env:
        LOG_LEVEL: debug

    - name: Set order status to failure
      uses: actions/github-script@v3
      if: failure()
      with:
        script: |
          return github.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: "An error occurred with the order: ${{ steps.Order-Pizza.outputs.Error_Message }}"
          })
